---
deployment:
  tasks:
    - export DEPLOYPATH=/home/storecen/public_html/news/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rsync -av --delete --exclude='.git' --exclude='.cpanel.yml' ./ $DEPLOYPATH
