export type CategoryType = 
  | 'Economia'
  | 'Política'
  | 'Negócios'
  | 'Tecnologia'
  | 'Geopolítica'
  | 'Nacional'
  | 'Esporte'
  | 'Saúde'
  | 'Entretenimento'
  | 'Judiciário';

export interface Post {
  id: string;
  title: string;
  subtitle: string;
  slug: string;
  content: string;
  category: CategoryType;
  tags: string[];
  author: string;
  date: string; // ISO string or YYYY-MM-DD HH:MM
  status: 'published' | 'draft' | 'scheduled';
  publishAt?: string; // for scheduled
  image: string; // URL or base64 or placeholder
  seoTitle: string;
  seoDescription: string;
  keyword: string;
  imagePrompt?: string; // prompt generated by IA
  imageSource?: string;
  imageOriginalUrl?: string;
  imageStrategy?: 'source-original' | 'page-original' | 'editorial-template' | 'curated-stock' | 'ai-generated';
  imageSubjectType?: 'person' | 'group' | 'generic';
  imageCredit?: string;
  imageLicense?: string;
  sourceUrl?: string;
  sourceName?: string;
  rssOriginalTitle?: string;
  views: number;
  isTestPost?: boolean;
  isUrgente?: boolean;
  isDestaque?: boolean;
}

export interface RSSFeed {
  id: string;
  name: string;
  url: string;
  category: CategoryType;
  status: 'active' | 'inactive';
  lastScraped?: string;
  imagePolicy?: 'reuse_with_credit' | 'reference_only' | 'no_reuse';
  imageLicense?: string;
  imageCreditTemplate?: string;
}

export interface AdUnit {
  id: string;
  name: string;
  slot: 'top' | 'middle' | 'bottom' | 'sidebar' | 'footer' | 'floating';
  code: string;
  enabled: boolean;
}

export interface SiteSettings {
  siteName: string;
  siteDescription: string;
  footerText: string;
  analyticsId: string;
  contactEmail: string;
}

export interface LinkComparisonResult {
  title: string;
  subtitle: string;
  content: string;
  seoTitle: string;
  seoDescription: string;
  tags: string[];
  category: CategoryType;
  conflicts: string; // Descrição de eventuais contradições, ou "Sem conflitos"
  imagePrompt: string;
  sourcesAnalyzed: string[];
}

export function getEditorialScore(post: Post): number {
  if (post.isTestPost) return 0;

  const baseViews = post.views || 0;
  let relevance = 0;

  const category = (post.category || '').toLowerCase();
  const title = (post.title || '').toLowerCase();
  const subtitle = (post.subtitle || '').toLowerCase();
  const content = (post.content || '').toLowerCase();
  const tags = (post.tags || []).map(t => t.toLowerCase());

  // Priority topics and matching rules
  const priorities = [
    { name: 'economia', points: 50 },
    { name: 'geopolítica', points: 50, terms: ['geopolítica', 'geopolitica', 'internacional', 'fronteira', 'guerra', 'acordo bilateral', 'tratado'] },
    { name: 'tecnologia', points: 50, terms: ['tecnologia', 'tech', 'inovação', 'digital'] },
    { name: 'inteligência artificial', points: 50, terms: ['inteligência artificial', 'inteligencia artificial', 'ia', 'gemini', 'gpt', 'ai', 'robótica', 'llm', 'machine learning'] },
    { name: 'energia', points: 50, terms: ['energia', 'petróleo', 'renovável', 'combustível', 'elétrica', 'solar', 'eólica', 'gas', 'gás'] },
    { name: 'política', points: 50, terms: ['política', 'politica', 'governo', 'senado', 'câmara', 'ministro', 'votação', 'eleição', 'eleições', 'lei', 'decreto'] }
  ];

  priorities.forEach(prio => {
    let matched = false;
    // Check main category
    if (category.includes(prio.name) || (prio.terms && prio.terms.some(t => category.includes(t)))) {
      matched = true;
    }
    // Check tags
    if (tags.some(tag => tag.includes(prio.name) || (prio.terms && prio.terms.some(t => tag.includes(t))))) {
      matched = true;
    }
    // Check title/subtitle/content keywords
    if (prio.terms && prio.terms.some(t => title.includes(t) || subtitle.includes(t))) {
      matched = true;
    }

    if (matched) {
      relevance += prio.points;
    }
  });

  return baseViews + relevance;
}

export function isPostUrgente(post: Post): boolean {
  if (post.isUrgente) return true;
  if (!post.date) return false;

  // Recency alone does not make a story urgent. It must carry an explicit
  // breaking-news signal and still be recent enough to justify the badge.
  const urgencyText = String((post.title || '') + ' ' + (post.tags || []).join(' ')).toLowerCase();
  const hasUrgencySignal = /\b(urgente|última hora|ultima hora|ao vivo|alerta)\b/.test(urgencyText);

  // Keep the explicit signal valid only while the story is still recent.
  const postTime = new Date(post.date).getTime();
  const now = new Date().getTime();
  const diffHours = (now - postTime) / (1000 * 60 * 60);

  return hasUrgencySignal && diffHours >= 0 && diffHours <= 12;
}

export const CATEGORY_FALLBACK_POOLS: Record<string, string[]> = {
  'Economia': [
    'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&h=480&q=80'
  ],
  'Tecnologia': [
    'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1472438971485-d6c69433dcb9?auto=format&fit=crop&w=800&h=480&q=80'
  ],
  'Geopolítica': [
    'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=800&h=480&q=80'
  ],
  'Negócios': [
    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1444653389962-8149286c578a?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&h=480&q=80'
  ],
  'Política': [
    'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1555848962-6e79363ec18f?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format&fit=crop&w=800&h=480&q=80'
  ],
  'Saúde': [
    'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1584515903407-3c15adfc17af?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1581594549595-35e6edbf75c7?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1579684389782-64d84b5e901a?auto=format&fit=crop&w=800&h=480&q=80'
  ],
  'Esporte': [
    'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1519766304817-4f37bda74a27?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1526676059637-250353088f1c?auto=format&fit=crop&w=800&h=480&q=80'
  ],
  'Entretenimento': [
    'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?auto=format&fit=crop&w=800&h=480&q=80'
  ],
  'Judiciário': [
    'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1453945619913-79ec89a82c51?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1505664194779-8beaceb93744?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1589994965851-a8f479c573a9?auto=format&fit=crop&w=800&h=480&q=80'
  ],
  'Nacional': [
    'https://images.unsplash.com/photo-1488085061387-422e29b40080?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&h=480&q=80',
    'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=800&h=480&q=80'
  ]
};

export function getDeterministicStringHash(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = str.charCodeAt(i) + ((hash << 5) - hash);
  }
  return Math.abs(hash);
}

function parsePostDateValue(value: unknown): Date | null {
  if (!value) return null;
  if (value instanceof Date) return isNaN(value.getTime()) ? null : value;

  const text = String(value).trim();
  const brazilianDate = text.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})(?:[ T](\d{1,2}):(\d{2})(?::(\d{2}))?)?$/);
  if (brazilianDate) {
    const [, day, month, year, hour = '0', minute = '0', second = '0'] = brazilianDate;
    const parsed = new Date(Date.UTC(+year, +month - 1, +day, +hour, +minute, +second));
    return isNaN(parsed.getTime()) ? null : parsed;
  }

  const parsed = new Date(text);
  return isNaN(parsed.getTime()) ? null : parsed;
}

export function getResolvedPostDate(post: any): string {
  if (!post) return '1970-01-01T00:00:00.000Z';
  
  // Priority rule specified: 1. publishedAt, 2. updatedAt, 3. createdAt, 4. date
  const candidates = [post.publishedAt, post.updatedAt, post.createdAt, post.date];
  const now = new Date();
  
  for (const val of candidates) {
    if (val) {
      const parsed = parsePostDateValue(val);
      if (parsed && parsed.getTime() > 0) {
        const isScheduled = String(post.status || '').trim().toLowerCase() === 'scheduled';
        if (!isScheduled && parsed.getTime() > now.getTime()) {
          continue; // Try next priority candidates first
        }
        return parsed.toISOString();
      }
    }
  }

  // Fallback: If all candidates exist but were invalid or future caps, return the first valid candidate ISO
  for (const val of candidates) {
    if (val) {
      const parsed = parsePostDateValue(val);
      if (parsed && parsed.getTime() > 0) {
        return parsed.toISOString();
      }
    }
  }

  return '1970-01-01T00:00:00.000Z';
}

export function getPostTimestamp(post: any): number {
  if (!post) return 0;
  // Priority rule specified: 1. publishedAt, 2. updatedAt, 3. createdAt, 4. date
  const candidates = [post.publishedAt, post.updatedAt, post.createdAt, post.date];
  for (const val of candidates) {
    if (val) {
      const parsed = parsePostDateValue(val);
      const t = parsed?.getTime() || 0;
      if (t > 0) {
        return t;
      }
    }
  }
  return 0; // Se a data for inválida, usar 0
}

export function getCategoryFallbackImage(category?: string, seedStr?: string, avoidUrls: Set<string> = new Set()): string {
  const cat = String(category || '').trim();
  const covers: Record<string, string> = {
    Economia: '/assets/editorial/economia.svg',
    Negócios: '/assets/editorial/economia.svg',
    Política: '/assets/editorial/politica.svg',
    Judiciário: '/assets/editorial/politica.svg',
    Direito: '/assets/editorial/politica.svg',
    Tecnologia: '/assets/editorial/tecnologia.svg',
    Esporte: '/assets/editorial/esporte.svg',
    Geopolítica: '/assets/editorial/geral.svg',
    Nacional: '/assets/editorial/geral.svg',
    Saúde: '/assets/editorial/geral.svg',
    Entretenimento: '/assets/editorial/geral.svg',
    Cultura: '/assets/editorial/geral.svg'
  };
  return covers[cat] || covers.Nacional;
}

export function normalizePost(post: any): Post {
  if (!post) return post;
  const p = { ...post };

  // Marcadores usados internamente na consolidação de fontes nunca devem ser
  // exibidos ao leitor (inclusive na cópia estática do portal).
  if (typeof p.title === 'string') {
    p.title = p.title
      .replace(/^\s*\[?Fonte\s*["'“”]?\s*1\]?\s*[:\-—]?\s*/i, '')
      .split(/\s*\[?Fonte\s*2\]?\b/i)[0]
      .trim();
  }

  // Normalize status - handle "NO AR", boolean "published"
  const rawStatus = String(p.status || '').trim().toLowerCase();
  
  if (
    rawStatus === 'published' || 
    rawStatus === 'no ar' || 
    rawStatus === 'no_ar' || 
    p.published === true || 
    p.published === 'true'
  ) {
    p.status = 'published';
  } else if (rawStatus === 'scheduled') {
    p.status = 'scheduled';
  } else {
    p.status = 'draft';
  }

  // Normalize date using our strict priority-based validator
  p.date = getResolvedPostDate(p);

  // Normalize scheduling fields
  if (p.status === 'scheduled') {
    if (!p.publishAt) {
      p.publishAt = p.scheduledAt || p.publishAt;
    }
    // If the scheduled date has already passed, treat it as published!
    if (p.publishAt) {
      const parsedPublish = new Date(p.publishAt);
      if (!isNaN(parsedPublish.getTime()) && parsedPublish <= new Date()) {
        p.status = 'published';
        p.date = parsedPublish.toISOString(); // Set published date to match its scheduled publish time
      }
    }
  }

  // Ensure views is a number
  if (typeof p.views !== 'number') {
    p.views = Number(p.views) || 0;
  }

  // Ensure tags is an array
  if (!p.tags) {
    p.tags = [];
  } else if (typeof p.tags === 'string') {
    p.tags = (p.tags as string).split(',').map(t => t.trim()).filter(Boolean);
  }

  // Only explicit internal markers identify a test post. Editorial uses of the word
  // "teste" (for example, a vehicle review) are legitimate news headlines.
  const titleLower = String(p.title || '').trim().toLowerCase();
  const isTestByTitle =
    /^\[(?:teste|test)\](?:\s|$)/i.test(titleLower) ||
    /^(?:test post|test_post)(?:\s|:|-|$)/i.test(titleLower) ||
    /^teste\s+(?:interno|autom[aá]tico)(?:\s|:|-|$)/i.test(titleLower);
  
  if (p.isTestPost === 'true' || p.isTestPost === true || isTestByTitle) {
    p.isTestPost = true;
  } else {
    p.isTestPost = false;
  }

  return p as Post;
}
