export type CategoryType = 
  | 'Economia'
  | 'Política'
  | 'Negócios'
  | 'Tecnologia'
  | 'Geopolítica'
  | 'Nacional'
  | 'Esporte'
  | 'Saúde'
  | 'Entretenimento';

export interface Post {
  id: string;
  title: string;
  subtitle: string;
  slug: string;
  content: string;
  category: CategoryType;
  tags: string[];
  author: string;
  date: string; // ISO string or YYYY-MM-DD HH:MM
  status: 'published' | 'draft' | 'scheduled';
  publishAt?: string; // for scheduled
  image: string; // URL or base64 or placeholder
  seoTitle: string;
  seoDescription: string;
  keyword: string;
  imagePrompt?: string; // prompt generated by IA
  views: number;
  isTestPost?: boolean;
  isUrgente?: boolean;
}

export interface RSSFeed {
  id: string;
  name: string;
  url: string;
  category: CategoryType;
  status: 'active' | 'inactive';
  lastScraped?: string;
}

export interface AdUnit {
  id: string;
  name: string;
  slot: 'top' | 'middle' | 'bottom' | 'sidebar' | 'footer' | 'floating';
  code: string;
  enabled: boolean;
}

export interface SiteSettings {
  siteName: string;
  siteDescription: string;
  footerText: string;
  analyticsId: string;
  contactEmail: string;
}

export interface LinkComparisonResult {
  title: string;
  subtitle: string;
  content: string;
  seoTitle: string;
  seoDescription: string;
  tags: string[];
  category: CategoryType;
  conflicts: string; // Descrição de eventuais contradições, ou "Sem conflitos"
  imagePrompt: string;
  sourcesAnalyzed: string[];
}

export function getEditorialScore(post: Post): number {
  if (post.isTestPost) return 0;

  const baseViews = post.views || 0;
  let relevance = 0;

  const category = (post.category || '').toLowerCase();
  const title = (post.title || '').toLowerCase();
  const subtitle = (post.subtitle || '').toLowerCase();
  const content = (post.content || '').toLowerCase();
  const tags = (post.tags || []).map(t => t.toLowerCase());

  // Priority topics and matching rules
  const priorities = [
    { name: 'economia', points: 50 },
    { name: 'geopolítica', points: 50, terms: ['geopolítica', 'geopolitica', 'internacional', 'fronteira', 'guerra', 'acordo bilateral', 'tratado'] },
    { name: 'tecnologia', points: 50, terms: ['tecnologia', 'tech', 'inovação', 'digital'] },
    { name: 'inteligência artificial', points: 50, terms: ['inteligência artificial', 'inteligencia artificial', 'ia', 'gemini', 'gpt', 'ai', 'robótica', 'llm', 'machine learning'] },
    { name: 'energia', points: 50, terms: ['energia', 'petróleo', 'renovável', 'combustível', 'elétrica', 'solar', 'eólica', 'gas', 'gás'] },
    { name: 'política', points: 50, terms: ['política', 'politica', 'governo', 'senado', 'câmara', 'ministro', 'votação', 'eleição', 'eleições', 'lei', 'decreto'] }
  ];

  priorities.forEach(prio => {
    let matched = false;
    // Check main category
    if (category.includes(prio.name) || (prio.terms && prio.terms.some(t => category.includes(t)))) {
      matched = true;
    }
    // Check tags
    if (tags.some(tag => tag.includes(prio.name) || (prio.terms && prio.terms.some(t => tag.includes(t))))) {
      matched = true;
    }
    // Check title/subtitle/content keywords
    if (prio.terms && prio.terms.some(t => title.includes(t) || subtitle.includes(t))) {
      matched = true;
    }

    if (matched) {
      relevance += prio.points;
    }
  });

  return baseViews + relevance;
}

export function isPostUrgente(post: Post): boolean {
  if (post.isUrgente) return true;
  if (!post.date) return false;

  // Check if title or tags contains urgent keywords
  const hasUrgenteKeyword = String((post.title || '') + ' ' + (post.tags || []).join(' ')).toLowerCase().includes('urgente');

  // Check if published in the last 24 hours (notícias quentes)
  const postTime = new Date(post.date).getTime();
  const now = new Date().getTime();
  const diffHours = (now - postTime) / (1000 * 60 * 60);

  return hasUrgenteKeyword || (diffHours >= 0 && diffHours <= 24);
}

export function getCategoryFallbackImage(category?: string): string {
  const cat = String(category || '').trim();
  switch (cat) {
    case 'Economia':
      return 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1280&h=720&q=80';
    case 'Tecnologia':
      return 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1280&h=720&q=80';
    case 'Geopolítica':
      return 'https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=1280&h=720&q=80';
    case 'Negócios':
      return 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1280&h=720&q=80';
    case 'Política':
      return 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?auto=format&fit=crop&w=1280&h=720&q=80';
    case 'Saúde':
      return 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1280&h=720&q=80';
    case 'Esporte':
      return 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1280&h=720&q=80';
    case 'Entretenimento':
      return 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1280&h=720&q=80';
    case 'Nacional':
    default:
      return 'https://images.unsplash.com/photo-1488085061387-422e29b40080?auto=format&fit=crop&w=1280&h=720&q=80';
  }
}

export function normalizePost(post: any): Post {
  if (!post) return post;
  const p = { ...post };

  // Normalize status - handle "NO AR", boolean "published"
  const rawStatus = String(p.status || '').trim().toLowerCase();
  
  if (
    rawStatus === 'published' || 
    rawStatus === 'no ar' || 
    rawStatus === 'no_ar' || 
    p.published === true || 
    p.published === 'true'
  ) {
    p.status = 'published';
  } else if (rawStatus === 'scheduled') {
    p.status = 'scheduled';
  } else {
    p.status = 'draft';
  }

  // Normalize date - prioritize publishedAt (most progressive), then date, then createdAt
  const resolvedDate = p.publishedAt || p.date || p.createdAt || new Date().toISOString();
  p.date = resolvedDate;

  // Normalize scheduling fields
  if (p.status === 'scheduled') {
    if (!p.publishAt) {
      p.publishAt = p.scheduledAt || p.publishAt;
    }
    // If the scheduled date has already passed, treat it as published!
    if (p.publishAt && new Date(p.publishAt) <= new Date()) {
      p.status = 'published';
      p.date = p.publishAt; // Set published date to match its scheduled publish time
    }
  }

  // Ensure views is a number
  if (typeof p.views !== 'number') {
    p.views = Number(p.views) || 0;
  }

  // Ensure tags is an array
  if (!p.tags) {
    p.tags = [];
  } else if (typeof p.tags === 'string') {
    p.tags = (p.tags as string).split(',').map(t => t.trim()).filter(Boolean);
  }

  // Ensure isTestPost is a boolean, detecting by "teste" keyword in titles to prevent test posts leaking
  const titleLower = String(p.title || '').trim().toLowerCase();
  const isTestByTitle = titleLower.includes('teste') || titleLower.includes('test post') || titleLower.includes('test_post');
  if (p.isTestPost === 'true' || p.isTestPost === true || isTestByTitle) {
    p.isTestPost = true;
  } else {
    p.isTestPost = false;
  }

  return p as Post;
}



