name: Store Center RSS Auto

on:
  schedule:
    - cron: "7,52 0-23/3 * * *"
    - cron: "37 1-23/3 * * *"
    - cron: "22 2-23/3 * * *"
  workflow_dispatch:

jobs:
  rss-auto:
    runs-on: ubuntu-latest
    steps:
      - name: Executar RSS automático do Store Center
        run: |
          curl -L --fail --show-error "https://www.storecenter.com.br/api/cron/rss-auto"
